CREATE TABLE [dbo].[Roles] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	[Description] NVARCHAR(255) NULL,
	[CreatedDate] DATETIME2 DEFAULT GETDATE(),
	[ModifyDate] DATETIME2 DEFAULT GETDATE(),
	[IsActive] BIT DEFAULT 1
);