CREATE TABLE [dbo].[Users] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Username] NVARCHAR(50) NOT NULL UNIQUE,
	[PasswordHash] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[CreatedDate] DATETIME2 DEFAULT GETDATE(),
	[ModifyDate] DATETIME2 DEFAULT GETDATE(),
	[IsActive] BIT DEFAULT 1,
	[LastLoginAttempt] DATETIME2 NULL,
	[FailedLoginAttempts] INT DEFAULT 0,
	[RoleId] UNIQUEIDENTIFIER NOT NULL,
);